/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Block } from './Block';
import {
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
    BlockToJSONTyped,
} from './Block';

/**
 * 
 * @export
 * @interface AppendBlockChildrenResponse
 */
export interface AppendBlockChildrenResponse {
    /**
     * 
     * @type {string}
     * @memberof AppendBlockChildrenResponse
     */
    object?: AppendBlockChildrenResponseObjectEnum;
    /**
     * 
     * @type {Array<Block>}
     * @memberof AppendBlockChildrenResponse
     */
    results?: Array<Block>;
    /**
     * 下一页游标，使用最后一个项目的ID作为游标值
     * @type {string}
     * @memberof AppendBlockChildrenResponse
     */
    next_cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AppendBlockChildrenResponse
     */
    has_more?: boolean;
}


/**
 * @export
 */
export const AppendBlockChildrenResponseObjectEnum = {
    List: 'list'
} as const;
export type AppendBlockChildrenResponseObjectEnum = typeof AppendBlockChildrenResponseObjectEnum[keyof typeof AppendBlockChildrenResponseObjectEnum];


/**
 * Check if a given object implements the AppendBlockChildrenResponse interface.
 */
export function instanceOfAppendBlockChildrenResponse(value: object): value is AppendBlockChildrenResponse {
    return true;
}

export function AppendBlockChildrenResponseFromJSON(json: any): AppendBlockChildrenResponse {
    return AppendBlockChildrenResponseFromJSONTyped(json, false);
}

export function AppendBlockChildrenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppendBlockChildrenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(BlockFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'] == null ? undefined : json['has_more'],
    };
}

export function AppendBlockChildrenResponseToJSON(json: any): AppendBlockChildrenResponse {
    return AppendBlockChildrenResponseToJSONTyped(json, false);
}

export function AppendBlockChildrenResponseToJSONTyped(value?: AppendBlockChildrenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(BlockToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

