/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 内部文件信息
 * @export
 * @interface BlockDataFile
 */
export interface BlockDataFile {
    /**
     * 
     * @type {string}
     * @memberof BlockDataFile
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof BlockDataFile
     */
    expiry_time?: Date;
}

/**
 * Check if a given object implements the BlockDataFile interface.
 */
export function instanceOfBlockDataFile(value: object): value is BlockDataFile {
    return true;
}

export function BlockDataFileFromJSON(json: any): BlockDataFile {
    return BlockDataFileFromJSONTyped(json, false);
}

export function BlockDataFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDataFile {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'expiry_time': json['expiry_time'] == null ? undefined : (new Date(json['expiry_time'])),
    };
}

export function BlockDataFileToJSON(json: any): BlockDataFile {
    return BlockDataFileToJSONTyped(json, false);
}

export function BlockDataFileToJSONTyped(value?: BlockDataFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'expiry_time': value['expiry_time'] == null ? undefined : ((value['expiry_time']).toISOString()),
    };
}

