/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 外部链接信息
 * @export
 * @interface BlockDataExternal
 */
export interface BlockDataExternal {
    /**
     * 
     * @type {string}
     * @memberof BlockDataExternal
     */
    url?: string;
}

/**
 * Check if a given object implements the BlockDataExternal interface.
 */
export function instanceOfBlockDataExternal(value: object): value is BlockDataExternal {
    return true;
}

export function BlockDataExternalFromJSON(json: any): BlockDataExternal {
    return BlockDataExternalFromJSONTyped(json, false);
}

export function BlockDataExternalFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDataExternal {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function BlockDataExternalToJSON(json: any): BlockDataExternal {
    return BlockDataExternalToJSONTyped(json, false);
}

export function BlockDataExternalToJSONTyped(value?: BlockDataExternal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

