/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePagePropertyValueFilesFilesInnerExternal
 */
export interface CreatePagePropertyValueFilesFilesInnerExternal {
    /**
     * 
     * @type {string}
     * @memberof CreatePagePropertyValueFilesFilesInnerExternal
     */
    url: string;
}

/**
 * Check if a given object implements the CreatePagePropertyValueFilesFilesInnerExternal interface.
 */
export function instanceOfCreatePagePropertyValueFilesFilesInnerExternal(value: object): value is CreatePagePropertyValueFilesFilesInnerExternal {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreatePagePropertyValueFilesFilesInnerExternalFromJSON(json: any): CreatePagePropertyValueFilesFilesInnerExternal {
    return CreatePagePropertyValueFilesFilesInnerExternalFromJSONTyped(json, false);
}

export function CreatePagePropertyValueFilesFilesInnerExternalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePagePropertyValueFilesFilesInnerExternal {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function CreatePagePropertyValueFilesFilesInnerExternalToJSON(json: any): CreatePagePropertyValueFilesFilesInnerExternal {
    return CreatePagePropertyValueFilesFilesInnerExternalToJSONTyped(json, false);
}

export function CreatePagePropertyValueFilesFilesInnerExternalToJSONTyped(value?: CreatePagePropertyValueFilesFilesInnerExternal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

