/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePagePropertyValuePeoplePeopleInner
 */
export interface CreatePagePropertyValuePeoplePeopleInner {
    /**
     * 
     * @type {string}
     * @memberof CreatePagePropertyValuePeoplePeopleInner
     */
    object?: CreatePagePropertyValuePeoplePeopleInnerObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof CreatePagePropertyValuePeoplePeopleInner
     */
    id: string;
}


/**
 * @export
 */
export const CreatePagePropertyValuePeoplePeopleInnerObjectEnum = {
    User: 'user'
} as const;
export type CreatePagePropertyValuePeoplePeopleInnerObjectEnum = typeof CreatePagePropertyValuePeoplePeopleInnerObjectEnum[keyof typeof CreatePagePropertyValuePeoplePeopleInnerObjectEnum];


/**
 * Check if a given object implements the CreatePagePropertyValuePeoplePeopleInner interface.
 */
export function instanceOfCreatePagePropertyValuePeoplePeopleInner(value: object): value is CreatePagePropertyValuePeoplePeopleInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreatePagePropertyValuePeoplePeopleInnerFromJSON(json: any): CreatePagePropertyValuePeoplePeopleInner {
    return CreatePagePropertyValuePeoplePeopleInnerFromJSONTyped(json, false);
}

export function CreatePagePropertyValuePeoplePeopleInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePagePropertyValuePeoplePeopleInner {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'id': json['id'],
    };
}

export function CreatePagePropertyValuePeoplePeopleInnerToJSON(json: any): CreatePagePropertyValuePeoplePeopleInner {
    return CreatePagePropertyValuePeoplePeopleInnerToJSONTyped(json, false);
}

export function CreatePagePropertyValuePeoplePeopleInnerToJSONTyped(value?: CreatePagePropertyValuePeoplePeopleInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'id': value['id'],
    };
}

