/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreatePagePropertyValueCheckbox } from './CreatePagePropertyValueCheckbox';
import {
    instanceOfCreatePagePropertyValueCheckbox,
    CreatePagePropertyValueCheckboxFromJSON,
    CreatePagePropertyValueCheckboxFromJSONTyped,
    CreatePagePropertyValueCheckboxToJSON,
} from './CreatePagePropertyValueCheckbox';
import type { CreatePagePropertyValueDate } from './CreatePagePropertyValueDate';
import {
    instanceOfCreatePagePropertyValueDate,
    CreatePagePropertyValueDateFromJSON,
    CreatePagePropertyValueDateFromJSONTyped,
    CreatePagePropertyValueDateToJSON,
} from './CreatePagePropertyValueDate';
import type { CreatePagePropertyValueEmail } from './CreatePagePropertyValueEmail';
import {
    instanceOfCreatePagePropertyValueEmail,
    CreatePagePropertyValueEmailFromJSON,
    CreatePagePropertyValueEmailFromJSONTyped,
    CreatePagePropertyValueEmailToJSON,
} from './CreatePagePropertyValueEmail';
import type { CreatePagePropertyValueFiles } from './CreatePagePropertyValueFiles';
import {
    instanceOfCreatePagePropertyValueFiles,
    CreatePagePropertyValueFilesFromJSON,
    CreatePagePropertyValueFilesFromJSONTyped,
    CreatePagePropertyValueFilesToJSON,
} from './CreatePagePropertyValueFiles';
import type { CreatePagePropertyValueMultiSelect } from './CreatePagePropertyValueMultiSelect';
import {
    instanceOfCreatePagePropertyValueMultiSelect,
    CreatePagePropertyValueMultiSelectFromJSON,
    CreatePagePropertyValueMultiSelectFromJSONTyped,
    CreatePagePropertyValueMultiSelectToJSON,
} from './CreatePagePropertyValueMultiSelect';
import type { CreatePagePropertyValueNumber } from './CreatePagePropertyValueNumber';
import {
    instanceOfCreatePagePropertyValueNumber,
    CreatePagePropertyValueNumberFromJSON,
    CreatePagePropertyValueNumberFromJSONTyped,
    CreatePagePropertyValueNumberToJSON,
} from './CreatePagePropertyValueNumber';
import type { CreatePagePropertyValuePeople } from './CreatePagePropertyValuePeople';
import {
    instanceOfCreatePagePropertyValuePeople,
    CreatePagePropertyValuePeopleFromJSON,
    CreatePagePropertyValuePeopleFromJSONTyped,
    CreatePagePropertyValuePeopleToJSON,
} from './CreatePagePropertyValuePeople';
import type { CreatePagePropertyValuePhoneNumber } from './CreatePagePropertyValuePhoneNumber';
import {
    instanceOfCreatePagePropertyValuePhoneNumber,
    CreatePagePropertyValuePhoneNumberFromJSON,
    CreatePagePropertyValuePhoneNumberFromJSONTyped,
    CreatePagePropertyValuePhoneNumberToJSON,
} from './CreatePagePropertyValuePhoneNumber';
import type { CreatePagePropertyValueRelation } from './CreatePagePropertyValueRelation';
import {
    instanceOfCreatePagePropertyValueRelation,
    CreatePagePropertyValueRelationFromJSON,
    CreatePagePropertyValueRelationFromJSONTyped,
    CreatePagePropertyValueRelationToJSON,
} from './CreatePagePropertyValueRelation';
import type { CreatePagePropertyValueRichText } from './CreatePagePropertyValueRichText';
import {
    instanceOfCreatePagePropertyValueRichText,
    CreatePagePropertyValueRichTextFromJSON,
    CreatePagePropertyValueRichTextFromJSONTyped,
    CreatePagePropertyValueRichTextToJSON,
} from './CreatePagePropertyValueRichText';
import type { CreatePagePropertyValueSelect } from './CreatePagePropertyValueSelect';
import {
    instanceOfCreatePagePropertyValueSelect,
    CreatePagePropertyValueSelectFromJSON,
    CreatePagePropertyValueSelectFromJSONTyped,
    CreatePagePropertyValueSelectToJSON,
} from './CreatePagePropertyValueSelect';
import type { CreatePagePropertyValueTitle } from './CreatePagePropertyValueTitle';
import {
    instanceOfCreatePagePropertyValueTitle,
    CreatePagePropertyValueTitleFromJSON,
    CreatePagePropertyValueTitleFromJSONTyped,
    CreatePagePropertyValueTitleToJSON,
} from './CreatePagePropertyValueTitle';
import type { CreatePagePropertyValueUrl } from './CreatePagePropertyValueUrl';
import {
    instanceOfCreatePagePropertyValueUrl,
    CreatePagePropertyValueUrlFromJSON,
    CreatePagePropertyValueUrlFromJSONTyped,
    CreatePagePropertyValueUrlToJSON,
} from './CreatePagePropertyValueUrl';

/**
 * @type CreatePagePropertyValue
 * 
 * @export
 */
export type CreatePagePropertyValue = CreatePagePropertyValueCheckbox | CreatePagePropertyValueDate | CreatePagePropertyValueEmail | CreatePagePropertyValueFiles | CreatePagePropertyValueMultiSelect | CreatePagePropertyValueNumber | CreatePagePropertyValuePeople | CreatePagePropertyValuePhoneNumber | CreatePagePropertyValueRelation | CreatePagePropertyValueRichText | CreatePagePropertyValueSelect | CreatePagePropertyValueTitle | CreatePagePropertyValueUrl;

export function CreatePagePropertyValueFromJSON(json: any): CreatePagePropertyValue {
    return CreatePagePropertyValueFromJSONTyped(json, false);
}

export function CreatePagePropertyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePagePropertyValue {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCreatePagePropertyValueCheckbox(json)) {
        return CreatePagePropertyValueCheckboxFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueDate(json)) {
        return CreatePagePropertyValueDateFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueEmail(json)) {
        return CreatePagePropertyValueEmailFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueFiles(json)) {
        return CreatePagePropertyValueFilesFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueMultiSelect(json)) {
        return CreatePagePropertyValueMultiSelectFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueNumber(json)) {
        return CreatePagePropertyValueNumberFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValuePeople(json)) {
        return CreatePagePropertyValuePeopleFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValuePhoneNumber(json)) {
        return CreatePagePropertyValuePhoneNumberFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueRelation(json)) {
        return CreatePagePropertyValueRelationFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueRichText(json)) {
        return CreatePagePropertyValueRichTextFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueSelect(json)) {
        return CreatePagePropertyValueSelectFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueTitle(json)) {
        return CreatePagePropertyValueTitleFromJSONTyped(json, true);
    }
    if (instanceOfCreatePagePropertyValueUrl(json)) {
        return CreatePagePropertyValueUrlFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CreatePagePropertyValueToJSON(json: any): any {
    return CreatePagePropertyValueToJSONTyped(json, false);
}

export function CreatePagePropertyValueToJSONTyped(value?: CreatePagePropertyValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCreatePagePropertyValueCheckbox(value)) {
        return CreatePagePropertyValueCheckboxToJSON(value as CreatePagePropertyValueCheckbox);
    }
    if (instanceOfCreatePagePropertyValueDate(value)) {
        return CreatePagePropertyValueDateToJSON(value as CreatePagePropertyValueDate);
    }
    if (instanceOfCreatePagePropertyValueEmail(value)) {
        return CreatePagePropertyValueEmailToJSON(value as CreatePagePropertyValueEmail);
    }
    if (instanceOfCreatePagePropertyValueFiles(value)) {
        return CreatePagePropertyValueFilesToJSON(value as CreatePagePropertyValueFiles);
    }
    if (instanceOfCreatePagePropertyValueMultiSelect(value)) {
        return CreatePagePropertyValueMultiSelectToJSON(value as CreatePagePropertyValueMultiSelect);
    }
    if (instanceOfCreatePagePropertyValueNumber(value)) {
        return CreatePagePropertyValueNumberToJSON(value as CreatePagePropertyValueNumber);
    }
    if (instanceOfCreatePagePropertyValuePeople(value)) {
        return CreatePagePropertyValuePeopleToJSON(value as CreatePagePropertyValuePeople);
    }
    if (instanceOfCreatePagePropertyValuePhoneNumber(value)) {
        return CreatePagePropertyValuePhoneNumberToJSON(value as CreatePagePropertyValuePhoneNumber);
    }
    if (instanceOfCreatePagePropertyValueRelation(value)) {
        return CreatePagePropertyValueRelationToJSON(value as CreatePagePropertyValueRelation);
    }
    if (instanceOfCreatePagePropertyValueRichText(value)) {
        return CreatePagePropertyValueRichTextToJSON(value as CreatePagePropertyValueRichText);
    }
    if (instanceOfCreatePagePropertyValueSelect(value)) {
        return CreatePagePropertyValueSelectToJSON(value as CreatePagePropertyValueSelect);
    }
    if (instanceOfCreatePagePropertyValueTitle(value)) {
        return CreatePagePropertyValueTitleToJSON(value as CreatePagePropertyValueTitle);
    }
    if (instanceOfCreatePagePropertyValueUrl(value)) {
        return CreatePagePropertyValueUrlToJSON(value as CreatePagePropertyValueUrl);
    }

    return {};
}

