/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IconExternalDetail
 */
export interface IconExternalDetail {
    /**
     * 
     * @type {string}
     * @memberof IconExternalDetail
     */
    url?: string;
}

/**
 * Check if a given object implements the IconExternalDetail interface.
 */
export function instanceOfIconExternalDetail(value: object): value is IconExternalDetail {
    return true;
}

export function IconExternalDetailFromJSON(json: any): IconExternalDetail {
    return IconExternalDetailFromJSONTyped(json, false);
}

export function IconExternalDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): IconExternalDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function IconExternalDetailToJSON(json: any): IconExternalDetail {
    return IconExternalDetailToJSONTyped(json, false);
}

export function IconExternalDetailToJSONTyped(value?: IconExternalDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

