/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverExternal } from './CoverExternal';
import {
    CoverExternalFromJSON,
    CoverExternalFromJSONTyped,
    CoverExternalToJSON,
    CoverExternalToJSONTyped,
} from './CoverExternal';

/**
 * 
 * @export
 * @interface PropertyValueFilesFilesInner
 */
export interface PropertyValueFilesFilesInner {
    /**
     * 
     * @type {string}
     * @memberof PropertyValueFilesFilesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyValueFilesFilesInner
     */
    type?: PropertyValueFilesFilesInnerTypeEnum;
    /**
     * 
     * @type {CoverExternal}
     * @memberof PropertyValueFilesFilesInner
     */
    external?: CoverExternal;
}


/**
 * @export
 */
export const PropertyValueFilesFilesInnerTypeEnum = {
    External: 'external'
} as const;
export type PropertyValueFilesFilesInnerTypeEnum = typeof PropertyValueFilesFilesInnerTypeEnum[keyof typeof PropertyValueFilesFilesInnerTypeEnum];


/**
 * Check if a given object implements the PropertyValueFilesFilesInner interface.
 */
export function instanceOfPropertyValueFilesFilesInner(value: object): value is PropertyValueFilesFilesInner {
    return true;
}

export function PropertyValueFilesFilesInnerFromJSON(json: any): PropertyValueFilesFilesInner {
    return PropertyValueFilesFilesInnerFromJSONTyped(json, false);
}

export function PropertyValueFilesFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValueFilesFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'external': json['external'] == null ? undefined : CoverExternalFromJSON(json['external']),
    };
}

export function PropertyValueFilesFilesInnerToJSON(json: any): PropertyValueFilesFilesInner {
    return PropertyValueFilesFilesInnerToJSONTyped(json, false);
}

export function PropertyValueFilesFilesInnerToJSONTyped(value?: PropertyValueFilesFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'external': CoverExternalToJSON(value['external']),
    };
}

