/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePagePropertyValueRelationRelationInner } from './CreatePagePropertyValueRelationRelationInner';
import {
    CreatePagePropertyValueRelationRelationInnerFromJSON,
    CreatePagePropertyValueRelationRelationInnerFromJSONTyped,
    CreatePagePropertyValueRelationRelationInnerToJSON,
    CreatePagePropertyValueRelationRelationInnerToJSONTyped,
} from './CreatePagePropertyValueRelationRelationInner';

/**
 * 
 * @export
 * @interface PropertyValueRelation
 */
export interface PropertyValueRelation {
    /**
     * 
     * @type {string}
     * @memberof PropertyValueRelation
     */
    id?: string;
    /**
     * 
     * @type {any}
     * @memberof PropertyValueRelation
     */
    type: any | null;
    /**
     * 
     * @type {Array<CreatePagePropertyValueRelationRelationInner>}
     * @memberof PropertyValueRelation
     */
    relation: Array<CreatePagePropertyValueRelationRelationInner>;
}

/**
 * Check if a given object implements the PropertyValueRelation interface.
 */
export function instanceOfPropertyValueRelation(value: object): value is PropertyValueRelation {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('relation' in value) || value['relation'] === undefined) return false;
    return true;
}

export function PropertyValueRelationFromJSON(json: any): PropertyValueRelation {
    return PropertyValueRelationFromJSONTyped(json, false);
}

export function PropertyValueRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValueRelation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'relation': ((json['relation'] as Array<any>).map(CreatePagePropertyValueRelationRelationInnerFromJSON)),
    };
}

export function PropertyValueRelationToJSON(json: any): PropertyValueRelation {
    return PropertyValueRelationToJSONTyped(json, false);
}

export function PropertyValueRelationToJSONTyped(value?: PropertyValueRelation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'relation': ((value['relation'] as Array<any>).map(CreatePagePropertyValueRelationRelationInnerToJSON)),
    };
}

