/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyValueSelectSelect } from './PropertyValueSelectSelect';
import {
    PropertyValueSelectSelectFromJSON,
    PropertyValueSelectSelectFromJSONTyped,
    PropertyValueSelectSelectToJSON,
    PropertyValueSelectSelectToJSONTyped,
} from './PropertyValueSelectSelect';

/**
 * 
 * @export
 * @interface PropertyValueSelect
 */
export interface PropertyValueSelect {
    /**
     * 
     * @type {string}
     * @memberof PropertyValueSelect
     */
    id?: string;
    /**
     * 
     * @type {any}
     * @memberof PropertyValueSelect
     */
    type?: any | null;
    /**
     * 
     * @type {PropertyValueSelectSelect}
     * @memberof PropertyValueSelect
     */
    select?: PropertyValueSelectSelect;
}

/**
 * Check if a given object implements the PropertyValueSelect interface.
 */
export function instanceOfPropertyValueSelect(value: object): value is PropertyValueSelect {
    return true;
}

export function PropertyValueSelectFromJSON(json: any): PropertyValueSelect {
    return PropertyValueSelectFromJSONTyped(json, false);
}

export function PropertyValueSelectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValueSelect {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'select': json['select'] == null ? undefined : PropertyValueSelectSelectFromJSON(json['select']),
    };
}

export function PropertyValueSelectToJSON(json: any): PropertyValueSelect {
    return PropertyValueSelectToJSONTyped(json, false);
}

export function PropertyValueSelectToJSONTyped(value?: PropertyValueSelect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'select': PropertyValueSelectSelectToJSON(value['select']),
    };
}

