/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RichTextItem } from './RichTextItem';
import {
    RichTextItemFromJSON,
    RichTextItemFromJSONTyped,
    RichTextItemToJSON,
    RichTextItemToJSONTyped,
} from './RichTextItem';

/**
 * 
 * @export
 * @interface PropertyValueRichText
 */
export interface PropertyValueRichText {
    /**
     * 
     * @type {string}
     * @memberof PropertyValueRichText
     */
    id?: string;
    /**
     * 
     * @type {any}
     * @memberof PropertyValueRichText
     */
    type?: any | null;
    /**
     * 
     * @type {Array<RichTextItem>}
     * @memberof PropertyValueRichText
     */
    rich_text?: Array<RichTextItem>;
}

/**
 * Check if a given object implements the PropertyValueRichText interface.
 */
export function instanceOfPropertyValueRichText(value: object): value is PropertyValueRichText {
    return true;
}

export function PropertyValueRichTextFromJSON(json: any): PropertyValueRichText {
    return PropertyValueRichTextFromJSONTyped(json, false);
}

export function PropertyValueRichTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValueRichText {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'rich_text': json['rich_text'] == null ? undefined : ((json['rich_text'] as Array<any>).map(RichTextItemFromJSON)),
    };
}

export function PropertyValueRichTextToJSON(json: any): PropertyValueRichText {
    return PropertyValueRichTextToJSONTyped(json, false);
}

export function PropertyValueRichTextToJSONTyped(value?: PropertyValueRichText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'rich_text': value['rich_text'] == null ? undefined : ((value['rich_text'] as Array<any>).map(RichTextItemToJSON)),
    };
}

