/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyValueCheckbox
 */
export interface PropertyValueCheckbox {
    /**
     * 
     * @type {string}
     * @memberof PropertyValueCheckbox
     */
    id?: string;
    /**
     * 
     * @type {any}
     * @memberof PropertyValueCheckbox
     */
    type?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyValueCheckbox
     */
    checkbox?: boolean;
}

/**
 * Check if a given object implements the PropertyValueCheckbox interface.
 */
export function instanceOfPropertyValueCheckbox(value: object): value is PropertyValueCheckbox {
    return true;
}

export function PropertyValueCheckboxFromJSON(json: any): PropertyValueCheckbox {
    return PropertyValueCheckboxFromJSONTyped(json, false);
}

export function PropertyValueCheckboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValueCheckbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'checkbox': json['checkbox'] == null ? undefined : json['checkbox'],
    };
}

export function PropertyValueCheckboxToJSON(json: any): PropertyValueCheckbox {
    return PropertyValueCheckboxToJSONTyped(json, false);
}

export function PropertyValueCheckboxToJSONTyped(value?: PropertyValueCheckbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'checkbox': value['checkbox'],
    };
}

