/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RichTextItem } from './RichTextItem';
import {
    RichTextItemFromJSON,
    RichTextItemFromJSONTyped,
    RichTextItemToJSON,
    RichTextItemToJSONTyped,
} from './RichTextItem';

/**
 * 
 * @export
 * @interface PropertyValueTitle
 */
export interface PropertyValueTitle {
    /**
     * 
     * @type {string}
     * @memberof PropertyValueTitle
     */
    id?: string;
    /**
     * 
     * @type {any}
     * @memberof PropertyValueTitle
     */
    type?: any | null;
    /**
     * 
     * @type {Array<RichTextItem>}
     * @memberof PropertyValueTitle
     */
    title?: Array<RichTextItem>;
}

/**
 * Check if a given object implements the PropertyValueTitle interface.
 */
export function instanceOfPropertyValueTitle(value: object): value is PropertyValueTitle {
    return true;
}

export function PropertyValueTitleFromJSON(json: any): PropertyValueTitle {
    return PropertyValueTitleFromJSONTyped(json, false);
}

export function PropertyValueTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyValueTitle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : ((json['title'] as Array<any>).map(RichTextItemFromJSON)),
    };
}

export function PropertyValueTitleToJSON(json: any): PropertyValueTitle {
    return PropertyValueTitleToJSONTyped(json, false);
}

export function PropertyValueTitleToJSONTyped(value?: PropertyValueTitle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'title': value['title'] == null ? undefined : ((value['title'] as Array<any>).map(RichTextItemToJSON)),
    };
}

