/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertySchemaTitle
 */
export interface PropertySchemaTitle {
    /**
     * 
     * @type {string}
     * @memberof PropertySchemaTitle
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertySchemaTitle
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof PropertySchemaTitle
     */
    type?: any | null;
    /**
     * 
     * @type {object}
     * @memberof PropertySchemaTitle
     */
    title?: object;
}

/**
 * Check if a given object implements the PropertySchemaTitle interface.
 */
export function instanceOfPropertySchemaTitle(value: object): value is PropertySchemaTitle {
    return true;
}

export function PropertySchemaTitleFromJSON(json: any): PropertySchemaTitle {
    return PropertySchemaTitleFromJSONTyped(json, false);
}

export function PropertySchemaTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertySchemaTitle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function PropertySchemaTitleToJSON(json: any): PropertySchemaTitle {
    return PropertySchemaTitleToJSONTyped(json, false);
}

export function PropertySchemaTitleToJSONTyped(value?: PropertySchemaTitle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'title': value['title'],
    };
}

