/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryDatabaseRequest
 */
export interface QueryDatabaseRequest {
    /**
     * 分页游标，使用页面ID作为游标值
     * @type {string}
     * @memberof QueryDatabaseRequest
     */
    start_cursor?: string;
    /**
     * 每页记录数
     * @type {number}
     * @memberof QueryDatabaseRequest
     */
    page_size?: number;
}

/**
 * Check if a given object implements the QueryDatabaseRequest interface.
 */
export function instanceOfQueryDatabaseRequest(value: object): value is QueryDatabaseRequest {
    return true;
}

export function QueryDatabaseRequestFromJSON(json: any): QueryDatabaseRequest {
    return QueryDatabaseRequestFromJSONTyped(json, false);
}

export function QueryDatabaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryDatabaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'start_cursor': json['start_cursor'] == null ? undefined : json['start_cursor'],
        'page_size': json['page_size'] == null ? undefined : json['page_size'],
    };
}

export function QueryDatabaseRequestToJSON(json: any): QueryDatabaseRequest {
    return QueryDatabaseRequestToJSONTyped(json, false);
}

export function QueryDatabaseRequestToJSONTyped(value?: QueryDatabaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_cursor': value['start_cursor'],
        'page_size': value['page_size'],
    };
}

