/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichTextItemMentionUser
 */
export interface RichTextItemMentionUser {
    /**
     * 
     * @type {string}
     * @memberof RichTextItemMentionUser
     */
    id?: string;
}

/**
 * Check if a given object implements the RichTextItemMentionUser interface.
 */
export function instanceOfRichTextItemMentionUser(value: object): value is RichTextItemMentionUser {
    return true;
}

export function RichTextItemMentionUserFromJSON(json: any): RichTextItemMentionUser {
    return RichTextItemMentionUserFromJSONTyped(json, false);
}

export function RichTextItemMentionUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichTextItemMentionUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function RichTextItemMentionUserToJSON(json: any): RichTextItemMentionUser {
    return RichTextItemMentionUserToJSONTyped(json, false);
}

export function RichTextItemMentionUserToJSONTyped(value?: RichTextItemMentionUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

