/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichTextItemMentionDate
 */
export interface RichTextItemMentionDate {
    /**
     * 
     * @type {string}
     * @memberof RichTextItemMentionDate
     */
    start?: string;
    /**
     * 
     * @type {string}
     * @memberof RichTextItemMentionDate
     */
    end?: string;
    /**
     * 
     * @type {string}
     * @memberof RichTextItemMentionDate
     */
    time_zone?: string;
}

/**
 * Check if a given object implements the RichTextItemMentionDate interface.
 */
export function instanceOfRichTextItemMentionDate(value: object): value is RichTextItemMentionDate {
    return true;
}

export function RichTextItemMentionDateFromJSON(json: any): RichTextItemMentionDate {
    return RichTextItemMentionDateFromJSONTyped(json, false);
}

export function RichTextItemMentionDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichTextItemMentionDate {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'time_zone': json['time_zone'] == null ? undefined : json['time_zone'],
    };
}

export function RichTextItemMentionDateToJSON(json: any): RichTextItemMentionDate {
    return RichTextItemMentionDateToJSONTyped(json, false);
}

export function RichTextItemMentionDateToJSONTyped(value?: RichTextItemMentionDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
        'time_zone': value['time_zone'],
    };
}

