/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichTextItemTextLink
 */
export interface RichTextItemTextLink {
    /**
     * 
     * @type {string}
     * @memberof RichTextItemTextLink
     */
    url?: string;
}

/**
 * Check if a given object implements the RichTextItemTextLink interface.
 */
export function instanceOfRichTextItemTextLink(value: object): value is RichTextItemTextLink {
    return true;
}

export function RichTextItemTextLinkFromJSON(json: any): RichTextItemTextLink {
    return RichTextItemTextLinkFromJSONTyped(json, false);
}

export function RichTextItemTextLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichTextItemTextLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function RichTextItemTextLinkToJSON(json: any): RichTextItemTextLink {
    return RichTextItemTextLinkToJSONTyped(json, false);
}

export function RichTextItemTextLinkToJSONTyped(value?: RichTextItemTextLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

