/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResultDataInner
 */
export interface SearchResultDataInner {
    /**
     * 页面或块的唯一标识符
     * @type {string}
     * @memberof SearchResultDataInner
     */
    uuid?: string;
    /**
     * 页面或块的标题
     * @type {string}
     * @memberof SearchResultDataInner
     */
    title?: string;
    /**
     * 页面或块的内容片段
     * @type {string}
     * @memberof SearchResultDataInner
     */
    content?: string;
    /**
     * 结果类型
     * @type {string}
     * @memberof SearchResultDataInner
     */
    type?: string;
}

/**
 * Check if a given object implements the SearchResultDataInner interface.
 */
export function instanceOfSearchResultDataInner(value: object): value is SearchResultDataInner {
    return true;
}

export function SearchResultDataInnerFromJSON(json: any): SearchResultDataInner {
    return SearchResultDataInnerFromJSONTyped(json, false);
}

export function SearchResultDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SearchResultDataInnerToJSON(json: any): SearchResultDataInner {
    return SearchResultDataInnerToJSONTyped(json, false);
}

export function SearchResultDataInnerToJSONTyped(value?: SearchResultDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'title': value['title'],
        'content': value['content'],
        'type': value['type'],
    };
}

