/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserMePerson
 */
export interface UserMePerson {
    /**
     * 用户邮箱地址
     * @type {string}
     * @memberof UserMePerson
     */
    email?: string;
}

/**
 * Check if a given object implements the UserMePerson interface.
 */
export function instanceOfUserMePerson(value: object): value is UserMePerson {
    return true;
}

export function UserMePersonFromJSON(json: any): UserMePerson {
    return UserMePersonFromJSONTyped(json, false);
}

export function UserMePersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMePerson {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UserMePersonToJSON(json: any): UserMePerson {
    return UserMePersonToJSONTyped(json, false);
}

export function UserMePersonToJSONTyped(value?: UserMePerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

