/* tslint:disable */
/* eslint-disable */
/**
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SearchPageResult } from './V1SearchPageResult';
import {
    V1SearchPageResultFromJSON,
    V1SearchPageResultFromJSONTyped,
    V1SearchPageResultToJSON,
    V1SearchPageResultToJSONTyped,
} from './V1SearchPageResult';

/**
 * 
 * @export
 * @interface V1SearchResponse
 */
export interface V1SearchResponse {
    /**
     * 
     * @type {string}
     * @memberof V1SearchResponse
     */
    object?: V1SearchResponseObjectEnum;
    /**
     * 搜索结果页面数组
     * @type {Array<V1SearchPageResult>}
     * @memberof V1SearchResponse
     */
    results?: Array<V1SearchPageResult>;
    /**
     * 下一页游标，为 null 表示没有更多结果
     * @type {string}
     * @memberof V1SearchResponse
     */
    next_cursor?: string;
    /**
     * 是否还有更多结果
     * @type {boolean}
     * @memberof V1SearchResponse
     */
    has_more?: boolean;
}


/**
 * @export
 */
export const V1SearchResponseObjectEnum = {
    List: 'list'
} as const;
export type V1SearchResponseObjectEnum = typeof V1SearchResponseObjectEnum[keyof typeof V1SearchResponseObjectEnum];


/**
 * Check if a given object implements the V1SearchResponse interface.
 */
export function instanceOfV1SearchResponse(value: object): value is V1SearchResponse {
    return true;
}

export function V1SearchResponseFromJSON(json: any): V1SearchResponse {
    return V1SearchResponseFromJSONTyped(json, false);
}

export function V1SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(V1SearchPageResultFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'] == null ? undefined : json['has_more'],
    };
}

export function V1SearchResponseToJSON(json: any): V1SearchResponse {
    return V1SearchResponseToJSONTyped(json, false);
}

export function V1SearchResponseToJSONTyped(value?: V1SearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(V1SearchPageResultToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

