/*
 * FlowUs API
 * FlowUs Developer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CreatePagePropertyValueSelectSelect;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreatePagePropertyValueSelect
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-29T21:44:43.879367+08:00[Asia/Shanghai]", comments = "Generator version: 7.14.0")
public class CreatePagePropertyValueSelect {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private Object type = null;

  public static final String SERIALIZED_NAME_SELECT = "select";
  @SerializedName(SERIALIZED_NAME_SELECT)
  @javax.annotation.Nonnull
  private CreatePagePropertyValueSelectSelect select;

  public CreatePagePropertyValueSelect() {
  }

  public CreatePagePropertyValueSelect type(@javax.annotation.Nullable Object type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public Object getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable Object type) {
    this.type = type;
  }


  public CreatePagePropertyValueSelect select(@javax.annotation.Nonnull CreatePagePropertyValueSelectSelect select) {
    this.select = select;
    return this;
  }

  /**
   * Get select
   * @return select
   */
  @javax.annotation.Nonnull
  public CreatePagePropertyValueSelectSelect getSelect() {
    return select;
  }

  public void setSelect(@javax.annotation.Nonnull CreatePagePropertyValueSelectSelect select) {
    this.select = select;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePagePropertyValueSelect createPagePropertyValueSelect = (CreatePagePropertyValueSelect) o;
    return Objects.equals(this.type, createPagePropertyValueSelect.type) &&
        Objects.equals(this.select, createPagePropertyValueSelect.select);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, select);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePagePropertyValueSelect {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    select: ").append(toIndentedString(select)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "select"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "select"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreatePagePropertyValueSelect
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreatePagePropertyValueSelect.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreatePagePropertyValueSelect is not found in the empty JSON string", CreatePagePropertyValueSelect.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreatePagePropertyValueSelect.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreatePagePropertyValueSelect` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreatePagePropertyValueSelect.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `select`
      CreatePagePropertyValueSelectSelect.validateJsonElement(jsonObj.get("select"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreatePagePropertyValueSelect.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreatePagePropertyValueSelect' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreatePagePropertyValueSelect> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreatePagePropertyValueSelect.class));

       return (TypeAdapter<T>) new TypeAdapter<CreatePagePropertyValueSelect>() {
           @Override
           public void write(JsonWriter out, CreatePagePropertyValueSelect value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreatePagePropertyValueSelect read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreatePagePropertyValueSelect given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreatePagePropertyValueSelect
   * @throws IOException if the JSON string is invalid with respect to CreatePagePropertyValueSelect
   */
  public static CreatePagePropertyValueSelect fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreatePagePropertyValueSelect.class);
  }

  /**
   * Convert an instance of CreatePagePropertyValueSelect to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

